### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by heldentodd** [rezasamarghandi/Kaula-F-and-G-functions#1]
Hi, thank you so much for coding these. It saved us a lot of time. We did find a typo in the code. There is one place in the code for the G function where -1 is exponentiated and needs to be in parentheses – that is (-1)^rp instead of -1^rp.

To be specific, line 39 of the Python code should read:
            plpq = plpq + binomial(2 * pp - 2 * l, hp - rp) * (((-1) ** rp) / factorial(rp)) * (

Similarly, line 62 of the Matlab code should be:
g=(-1)^abs(q-1)*(1+beta^2)^l*beta^abs(q)*symsum(symsum(nchoosek(2*pp-2*l,hp-rp)*(((-1)^rp)/factorial(rp))*((l-2*pp+qp)*e/(2*beta))^rp,rp,0,hp)*symsum(nchoosek(-2*pp,hq-rq)/factorial(rq)*((l-2*pp+qp)*e/(2*beta))^rq,rq,0,hq)*beta^(2*k),k,0,10);

Other than that, the code looks good. I think this is the negative of what Kaula defines in his book. That is line 62 of the Matlab code and line 46 of the Python code have the expression (-1)^abs(q-1), which I think should be (-1)^abs(q), but this is just a matter of sign convention.
Thanks again!

**Comment by rezasamarghandi** [comment]
Thank you so much for your comment. I've edited the codes and now they should all be correct.
